<a href="https://colab.research.google.com/github/anaskartaoui/french-gec/blob/dev/01n.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
from datasets import load_dataset
import pandas as pd


ds = load_dataset("akufeldt/fr-gec-dataset")

In [19]:
train_ds = ds['train']
print(train_ds[1])
count = train_ds.shape[0]
print(count)

columns = train_ds.column_names
print(columns)

{'lang': 'fr', 'sentence': 'Le regard est toujours franc et les carnations parfaites dans leurs teintes et leurs nuances.', 'modified': "fix grammar: L'regard est toujours franc et les parfaites carnations dans leurs teintes et leurs nuances.", 'transformation': 'AdjectiveMisplacerDestroyer', 'sec_transformation': 'ApostropheChangerDestroyer', '__index_level_0__': 5079}
59850
['lang', 'sentence', 'modified', 'transformation', 'sec_transformation', '__index_level_0__']

In [20]:
dev_ds = ds['dev']
print(dev_ds[1])
count = dev_ds.shape[0]
print(count)

{'lang': 'fr', 'sentence': "Le statut de l'ORTF était donc calqué sur celui de la BBC.", 'modified': "fix grammar: L'statut de le ORTF était donc calqué sur celui de l'BBC.", 'transformation': 'ApostropheChangerDestroyer', 'sec_transformation': None, '__index_level_0__': 2417}
3325

In [21]:
test_ds = ds['test']
print(test_ds[1])
count = test_ds.shape[0]
print(count)

{'lang': 'fr', 'sentence': "Le yérou à yer postérieur (capitale Ꙑ, minuscule ꙑ) est une lettre archaïque de l'", 'modified': "fix grammar: Le yérou en yer postérieur (capitale Ꙑ, minuscule ꙑ) est une lettre archaïque de l'", 'transformation': 'PrepositionReplacerDestroyer', 'sec_transformation': None, '__index_level_0__': 33099}
3325

In [22]:
train_ds.select(range(5)).to_pandas()

,lang,sentence,modified,transformation,sec_transformation,__index_level_0__
0,fr,"L'entrée au jardin est gratuite, sauf pour les...","fix grammar: Le entrée au jardin est gratuite,...",ApostropheChangerDestroyer,None,45114
1,fr,Le regard est toujours franc et les carnations...,fix grammar: L'regard est toujours franc et le...,AdjectiveMisplacerDestroyer,ApostropheChangerDestroyer,5079
2,fr,Vous êtes tout ce qu'ils ont.,fix grammar: Vous êtes tout ce que ils avons.,PersonVerbDisagreement,ApostropheChangerDestroyer,7746
3,fr,Sami s'est assis sur un siège côté couloir.,fix grammar: Sami sest assis sur un siège côté...,FrRemovePunctuationDestroyer,None,13925
4,fr,Milton Santos revint donc dans son pays d'orig...,fix grammar: Milton Santos revint donc en son ...,PrepositionReplacerDestroyer,None,7145

In [23]:
pd.Series(train_ds['transformation']).value_counts()

ApostropheChangerDestroyer        6687
PluralSingularNounDestroyer       6680
AdjectiveMisplacerDestroyer       6297
ContractionsDestroyer             5890
GenderDeterminerDestroyer         5287
PluralDeterminerDestroyer         4700
PrepositionReplacerDestroyer      3912
PersonVerbDisagreement            3731
RemoveAccentsDestroyer            3504
FrRemovePunctuationDestroyer      3143
FrVerbNumberChanger               2920
PossessiveReplacerDestroyer       1982
ReflexivePronounRemover           1468
PasRemoverDestroyer               1241
AdjectiveGenderChangeDestroyer     940
RandomTypoDestroyOperation         729
RandomWordRemoveOperation          370
CapitalsDestroyer                  151
SimpleQuestionDestroyer            138
Name: count, dtype: int64